# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(840, 640)

        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)

        self.grpUn = QtWidgets.QGroupBox(Form)
        self.grpUn.setGeometry(QtCore.QRect(10, 10, 400, 300))
        self.grpUn.setObjectName("grpUn")
        self.btn1_1 = QtWidgets.QPushButton(self.grpUn)
        self.btn1_1.setGeometry(QtCore.QRect(80, 50, 250, 50))
        self.btn1_1.setObjectName("btn1_1")
        self.btn1_2 = QtWidgets.QPushButton(self.grpUn)
        self.btn1_2.setGeometry(QtCore.QRect(80, 120, 250, 50))
        self.btn1_2.setObjectName("btn1_2")
        self.lbl1_1 = QtWidgets.QLabel(self.grpUn)
        self.lbl1_1.setGeometry(QtCore.QRect(80, 200, 250, 30))
        self.lbl1_1.setFont(font)
        self.lbl1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl1_1.setObjectName("lbl1_1")
        self.lbl1_2 = QtWidgets.QLabel(self.grpUn)
        self.lbl1_2.setGeometry(QtCore.QRect(80, 240, 250, 30))
        self.lbl1_2.setFont(font)
        self.lbl1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl1_2.setObjectName("lbl1_2")
        self.grpTrois = QtWidgets.QGroupBox(Form)
        self.grpTrois.setGeometry(QtCore.QRect(430, 10, 400, 150))
        self.grpTrois.setObjectName("grpTrois")
        self.btn3_1 = QtWidgets.QPushButton(self.grpTrois)
        self.btn3_1.setGeometry(QtCore.QRect(80, 60, 250, 50))
        self.btn3_1.setObjectName("btn3_1")
        self.grpQuatre = QtWidgets.QGroupBox(Form)
        self.grpQuatre.setGeometry(QtCore.QRect(430, 160, 400, 150))
        self.grpQuatre.setObjectName("grpQuatre")
        self.btn4_1 = QtWidgets.QPushButton(self.grpQuatre)
        self.btn4_1.setGeometry(QtCore.QRect(80, 60, 250, 50))
        self.btn4_1.setObjectName("btn4_1")
        self.grpDeux = QtWidgets.QGroupBox(Form)
        self.grpDeux.setGeometry(QtCore.QRect(10, 320, 820, 300))
        self.grpDeux.setObjectName("grpDeux")
        self.btn2_1 = QtWidgets.QPushButton(self.grpDeux)
        self.btn2_1.setGeometry(QtCore.QRect(50, 40, 250, 50))
        self.btn2_1.setObjectName("btn2_1")
        self.btn2_2 = QtWidgets.QPushButton(self.grpDeux)
        self.btn2_2.setGeometry(QtCore.QRect(50, 120, 250, 50))
        self.btn2_2.setObjectName("btn2_2")
        self.btn2_4 = QtWidgets.QPushButton(self.grpDeux)
        self.btn2_4.setGeometry(QtCore.QRect(50, 200, 250, 50))
        self.btn2_4.setObjectName("btn2_4")
        self.grpDeuxTrois = QtWidgets.QGroupBox(self.grpDeux)
        self.grpDeuxTrois.setGeometry(QtCore.QRect(400, 40, 391, 221))
        self.grpDeuxTrois.setObjectName("grpDeuxTrois")
        self.btn2_3 = QtWidgets.QPushButton(self.grpDeuxTrois)
        self.btn2_3.setGeometry(QtCore.QRect(80, 150, 250, 50))
        self.btn2_3.setObjectName("btn2_3")
        self.lbl_2_3 = QtWidgets.QLabel(self.grpDeuxTrois)
        self.lbl_2_3.setGeometry(QtCore.QRect(80, 30, 250, 30))

        self.lbl_2_3.setFont(font)
        self.lbl_2_3.setObjectName("lbl_2_3")
        self.comboBox = QtWidgets.QComboBox(self.grpDeuxTrois)
        self.comboBox.setGeometry(QtCore.QRect(80, 80, 150, 30))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.grpUn.setTitle(_translate("Form", "1.Find Contour"))
        self.btn1_1.setText(_translate("Form", "1.1Draw Contour"))
        self.btn1_2.setText(_translate("Form", "1.2Count Coins"))
        self.lbl1_1.setText(_translate("Form", "There are ___ coins in coin01.jpg"))
        self.lbl1_2.setText(_translate("Form", "There are ___ coins in coin02.jpg"))
        self.grpTrois.setTitle(_translate("Form", "3.Augmented Reality"))
        self.btn3_1.setText(_translate("Form", "3.1Augmented Reality"))
        self.grpQuatre.setTitle(_translate("Form", "4.Stereo Display Map"))
        self.btn4_1.setText(_translate("Form", "4.1Stereo Display Map"))
        self.grpDeux.setTitle(_translate("Form", "2.Calibration"))
        self.btn2_1.setText(_translate("Form", "2.1Find Corners"))
        self.btn2_2.setText(_translate("Form", "2.2Find Intrinsic"))
        self.btn2_4.setText(_translate("Form", "2.4Find Distortion"))
        self.grpDeuxTrois.setTitle(_translate("Form", "2.3Find Extrinsic"))
        self.btn2_3.setText(_translate("Form", "2.3Find Extrinsic"))
        self.lbl_2_3.setText(_translate("Form", "Select Image"))

        # combobox
        lstNumber = [*range(1, 16, 1)]
        lstStr =  ["{:d}".format(x) for x in lstNumber]
        self.comboBox.addItems(lstStr)
